{% set name = "biocore" %}

package:
  name: "{{ name|lower }}"
  version: "{{ BIOCORE_VERSION }}"

source:
  path: ../../

build:
  noarch: python

requirements:
  host:
    - python
    - pip
    - pandas
    - numpy >=1.17
    - pyarrow >=15.0.0
    - packaging
  run:
    - python
    - pip
    - pandas
    - numpy >=1.17
    - pyarrow >=15.0.0
    - packaging

test:
  imports:
    - biocore

about:
  home: https://github.com/psmyth94/biocore
  license: Apache-2.0
  license_file: LICENSE
  summary: A helper library for common functions found in the bio-families of libraries.
